# Generated by Django 4.1.5 on 2023-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/blog/prod/category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/default.png', upload_to='images/blog/prod/post/'),
        ),
    ]
