# Generated by Django 4.1.5 on 2023-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_img_category_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog_cat_description',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
