# Generated by Django 4.1.5 on 2023-01-10 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('image_cat', models.ImageField(default='images/default.png', upload_to='images/portfolio/prod/category/')),
                ('projet_cat_description', models.TextField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/portfolio/certificats/')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('delivery_date', models.DateTimeField(auto_now=True, null=True)),
                ('delivrer_par', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=2500, null=True)),
                ('date_send', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-date_send'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('date_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_status', models.CharField(choices=[('En Cours', 'En Cours'), ('Terminé', 'Terminé'), ('Suspendu', 'Suspendu')], default='en_cours', max_length=30)),
                ('project_thumbnail', models.ImageField(default='images/default.png', upload_to='images/portfolio/prod/project/')),
                ('project_url', models.URLField(blank=True, default='#', null=True)),
                ('git_url', models.URLField(blank=True, default='#', null=True)),
                ('project_goal', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_projects', to='portfolio.categorie')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_created_on'],
            },
        ),
    ]
