# Generated by Django 4.1.5 on 2023-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('image_tag', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/portfolio/prod/tag/')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_projects', to='portfolio.tag'),
        ),
    ]
