# Generated by Django 4.1.5 on 2023-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_categorie_image_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/portfolio/production/project/'),
        ),
    ]
